# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f4f6d502cfcdbc9da39a8dd59dabfd6e00379a4f38991cce4857b7d5fa04fa50b1117315338ef7a4480944ccf0301d6b28f4f9794694295738794cd39c32a5ef

test:
  secret_key_base: c015bdbae67ec28bfca419d7bf4796e6e2b1ddc9b7662427be654e8254354474988b8b2df9f9338c93eda8276cbe7a295d4a66eb4f0e662d439147ec1bdd7a9b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
